### ISSUE TITLE
dashboard is not visible

### ISSUE THREAD

**Issue by cocoethx** [Glacier-Labs/node-bootstrap#5]
Last Submit Time N/A 
Although the Received Delegations and Total Verifications node is running, there is no increase and there is no problem in the logs.

**Comment by Bart200c** [comment]
Because it's not your turn, a random group of verifier nodes in the network is chosen by the smart contract (using Chainlink VRF) to check each task. There's no certainty that a particular verifier node will be picked for verification.

Hope you have the verifications now!

[FAQ](https://docs.glacier.io/getting-started/glacier-nodes/run-testnet-nodes/faq)
